
import { DenonConfig } from "https://deno.land/x/denon@2.4.4/mod.ts";

const config: DenonConfig = {
  scripts: {
    start: {
      cmd: "deno run --unstable --no-check src/server.ts",
    },
  },
  env: {
    PORT : "5000",
    // Generated by generate-random-md5-hash @ onlinehashtools.com
    TOKEN_SECRET: "1c076e41ff4dfb488c1635a87978517314b4f36b6289fd17954b1dfe58d1611dd826c1af7371d0a3cdc3b89373ab4b2444e6041203ceb28595725be36a0f82eace1ad5daaa635af85c2c8fbd8a362e387d65dcb01e78f9f8ddea36657af0e86d12f24dce27f12c58832103dd33101dc866853fab18b075a56c510826274e10a98eb616848e1e84c085b92bca0acc7e53dc03f4635f2bd3e2d44e5a571fcc0cd9"
  },
  allow: ["net", "env"]
};

export default config;